### ISSUE TITLE
unattended Install test fails as it unable to find the right serial log file to parse the end of test

### ISSUE THREAD

**Issue by sathnaga** [autotest/virt-test#2022]
Place it breaks:
https://github.com/autotest/virt-test/blob/master/virttest/tests/unattended_install.py#L1102
       try:
            serial_log_msg = open(log_file, 'r').read()
        except IOError:

Why it breaks:
because of it assumes the file name as (e:g:- serial-serial0-virt-tests-vm1.log)
https://github.com/autotest/virt-test/blob/master/virttest/tests/unattended_install.py#L1065

    log_file = utils_misc.get_path(test.debugdir,
                                   "serial-%s-%s.log" % (serial_name,
                                                         vm.name

From when:
Recently it got changed to (e:g:- serial-serial0-virt-tests-vm1-XXXX.log)
https://github.com/autotest/virt-test/blob/master/virttest/libvirt_vm.py#L874

        return "serial-%s-%s-%s.log" % (name, self.name,
                                        utils_misc.generate_random_string(4))

Commit introduced this issue:
https://github.com/autotest/virt-test/commit/b2a48d5601686af06c4945c3c4de16958aa57c29

Either we need to get the new file name feed to unattended_install.py or revert this patch.
Suggestions?
@lmr @cevich  @Hao-Liu

**Comment by Hao-Liu** [comment]
@sathnaga, I added a random suffix to serial log name to prevent a new serial flush away the last one, and didn't expect a reference to this file name. I'll see what I can do to make this right.

**Comment by Hao-Liu** [comment]
@sathnaga, Thanks for pointing out the issue. PR https://github.com/autotest/virt-test/pull/2023 should be able to fix this. Please help to check this.
